<div style="background: black; padding: 10px 250px"><img src="https://www.veldikompetens.se/wp-content/themes/consid/static/icons/VeldiKompetens_Logo_Web_Negative.svg" title="Veldi kompetens" /></div>

<hr><h1><center>Exercise 2a - Introduction to Numpy</center></h1>

<h3>Instructions </h3>

In this exercise you will learn how to create and use NumPy arrays and learn what advantages NumPy comes with when it comes to arrays. You might wonder what the differences between an array and list are. 

A list can consist of different datatypes while an array only consists of one datatype, and each nested element in the array must contain the same size. Lists consumes more memory than arrays and are often prefered for shorter sequence of data items. An array however, is more efficient on handling larger data sizes.

A NumPy array cannot contain values of different types. Since all elements are of the same type, there is no need to check the type of each element in the array during runtime. This is one of the reasons why a NumPy array is faster than a normal array. 

<h3> 1. Setup </h3>

Make sure to import the NumPy package. This is done by running the cell below.

In [1]:
import numpy as np

<h3> 2. Introduction to Numpy </h3>

<h4>2.1 The Basics </h4>

Start by creating a NumPy array by using np.array.

In [2]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9])
print(numpy_array)

[1 2 3 4 5 6 7 8 9]


Usually, if you want to increment all elements in a list by one, you would probably be using something like the code in the cell below.

In [3]:
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    
for i, _ in enumerate(python_list):
    python_list[i] += 1


print(python_list)

[2, 3, 4, 5, 6, 7, 8, 9, 10]


With a NumPy array, all operators on arrays apply elementwise. Therefore it is possible to increment all the elements in an array with very simple code.

In [4]:
print(numpy_array + 1) # Get all elements incremented by one.
print(numpy_array *2) # Get all elements multiplied by two.
print(numpy_array **2) # Get the square of all elements in the array.

[ 2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18]
[ 1  4  9 16 25 36 49 64 81]


If you would print numpy_array after running above cells, you would see that its value has not changed despite the code in the cell above. 

In [5]:
print(numpy_array)

[1 2 3 4 5 6 7 8 9]


To change the values in an array, make sure that you assign the array these new values as well. Numpy does this by Broadcasting (recommended optional reading)

In [6]:
# Changing the values in an array
numpy_array += 1 # Incrementing all elements by one.
numpy_array *= 2 # Multiplying all elements by 2.
numpy_array **= 2 # Squaring all elements in the array.

print(numpy_array)

[ 16  36  64 100 144 196 256 324 400]


<h4>2.2 Other operators </h4>

In [7]:
# Create an array with 20 elements and with value 1. 
numpy_array = np.ones(20)
print(numpy_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
# Create an array with 20 elements and with value 0.
numpy_array = np.zeros(20) 
print(numpy_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Create an array with 20 elements and with values 0-19.
numpy_array = np.arange(20) 
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
# Create an array with elements between 100-500 with spacing equal to 50.
numpy_array = np.arange(100, 500, 50)
print(numpy_array)

[100 150 200 250 300 350 400 450]


In [11]:
# Returns true/false for all values in the array. 
print(numpy_array > 300)

[False False False False False  True  True  True]


In [12]:
# Select all values from position 3 until position 10. This is called slicing.
print(numpy_array[3:10])

# When you use array[x:y], the x:th position will be included but the y:th position will be excluded. 

[250 300 350 400 450]


In [13]:
# Select all values from position 5 to the end of the array.

print(numpy_array[5:])

# Or from the beginning of the array to position 5

print(numpy_array[:5])

[350 400 450]
[100 150 200 250 300]


In [14]:
# You can use operations using arrays on arrays.
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("a + b: ", a+b)
print("a - b: ", a-b)
print("a * b: ", a*b)

a + b:  [11 22 33 44]
a - b:  [ 9 18 27 36]
a * b:  [ 10  40  90 160]


The above code only works if the two arrays have either the same amount of elements in them or if NumPy can successfully broadcast the smaller array to match the other. However, broadcasting only works if the arrays have the exact same number of elements or if the shorter array contains exactly one element. 

In [15]:
# For example, in the code below, both array a + array b and array a + array c will print the same output. 
# This is because NumPy matches the shape of array a by creating a new array containing repeating values 
# of the value in array c which in this case makes it identical to array b.

a = np.array([10, 20, 30, 40])
b = np.array([10, 10, 10, 10])
c = np.array(10)


print(a + b)
print(a + c)

[20 30 40 50]
[20 30 40 50]


In [16]:
# Sort an array by ascending.
unsorted_array = np.array([3, 8, 4, 7, 3, 7, 2, 2, 1 ,7, 9, 5, 3, 10, 8, 3, 6])

print(np.sort(unsorted_array))

[ 1  2  2  3  3  3  3  4  5  6  7  7  7  8  8  9 10]


<h4> 2.3 The shape and dimension of an array </h4>

A NumPy array can contain arrays with multiple dimensions. The arrays we have used so far is one dimensional arrays. You can also create a two dimensional array:

In [17]:
two_d_numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_numpy_array)

[[1 2 3]
 [4 5 6]]


Or  a three dimensional array:

In [18]:
three_d_numpy_array = np.array([[[1,2,3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(three_d_numpy_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Of course, you can have practically as many dimensions as you like. To check how many dimensions an array has, use .ndim.

In [19]:
print(three_d_numpy_array.ndim)

3


To get one specific element´s value in an array you need to specify the position of that element. To get the first element in a one dimensional array run the cell below.

In [20]:
print(numpy_array[0])

100


In a two dimensional array each element has two values for its position. To get the second value in the second array in a two dimensional array, run the code below.

In [21]:
print(two_d_numpy_array[1, 1])

5


And to get an individual element in a three dimensional array, you would need to use three values for the position.

In [22]:
print(three_d_numpy_array[1,0,2])

9


This is how the indexing of an element works with the three dimensional array above: 

three_d_numpy_array looks like this: <pre>[[[1,2,3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]</pre>

In the cell above we selected the index [1, 0, 2] and the output was 9.

The first number in the index [1, 0, 2] represents the first dimension. 
three_d_numpy_array contains two arrays:
<pre>[[1, 2, 3], [4, 5, 6]]</pre> and <pre>[[7, 8, 9], [10, 11, 12]]</pre>

We chose 1 as the first number in the index and therefore we have selected the second array which is 
<pre>[[7, 8, 9], [10, 11, 12]]</pre>

The second number in the index [1, 0, 2] represents the second dimension. It contains two arrays:
<pre>[7, 8, 9]</pre> and <pre>[10, 11, 12]</pre>

We selected 0 as the second number and the first array was chosen which is
<pre>[7, 8, 9]</pre>

Finally, the last number in [1, 0, 2] represents the third dimension and contains three values:
7 8 9 

We chose the number 2 which is the third value 9.

<h4> 2.4 Shape and reshape </h4>
To see how many elements an array has in each of its dimensions, use .shape.

In [23]:
shape_array = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [21, 22, 23, 24, 25]])
print(shape_array)
print(shape_array.shape)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
(3, 5)


In the above cell we get the output (3, 5) which means that the array has 3 elements in the first dimension<pre>[1, 2, 3, 4, 5], [11, 12, 13, 14, 15] and [21, 22, 23, 24, 25]</pre> and 5 elements in the second dimension, because each of those arrays contains 5 elements.

If we would want to reshape this array to have 5 elements in its first dimension and 3 in its second, we can use .reshape

In [24]:
shape_array = shape_array.reshape(5, 3)
print(shape_array)

[[ 1  2  3]
 [ 4  5 11]
 [12 13 14]
 [15 21 22]
 [23 24 25]]


Or one element in the first dimension and 15 in the second;

In [25]:
shape_array = shape_array.reshape(1, 15)
print(shape_array)

[[ 1  2  3  4  5 11 12 13 14 15 21 22 23 24 25]]


We cannot shape arrays however we would like. All arrays needs to have the same number of elements, so reshape(7,2) for example would not work on this array since it would not fit all 15 elements.

In [26]:
# You can also use np.transpose to reverse the order of an arrays shape.

transpose_array = np.ones((2, 3, 4))
print("Original shape : ", transpose_array.shape)
print("\n", transpose_array)

transpose_array = np.transpose(transpose_array)
print("\nTransposed shape : ", transpose_array.shape)
print("\n", transpose_array)

Original shape :  (2, 3, 4)

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Transposed shape :  (4, 3, 2)

 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


##### Axis

<pre>[[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]
 [70 75 80]]</pre>

Imagine that the above array consists of rows and columns where each array is a row and the first value in each array is the first column, the second value in each array is the second column and so on. To visualize, the rows are 
<pre>[ 10,  15,  20], [ 25,  30, 35], [40, 45, 50], [55, 60, 65], [70, 75, 80]</pre>
and the columns are
<pre> [10, 25, 40, 55, 70], [15, 30, 45, 60, 75], [20, 35, 50, 65, 80]</pre>

To understand the axis in NumPy, just imagine that axis = 0 is the columns and that axis = 1 is the rows. Axis in NumPy can be very useful:

In [27]:
axis_array = np.array([[ 75,  25,  55], [ 25,  30, 35], [40, 45, 50], [55, 5, 65], [70, 75, 10]])
print(axis_array.min(axis = 0)) #Get the minimum value of each column.
print(axis_array.sum(axis = 1)) #Get the sum of each row.

[25  5 10]
[155  90 135 125 155]


Axis works a bit different with arrays that are not two dimensional. But for now you only need to know how axis works with two dimensional arrays.

<h4> 2.5 Slice, stack and insert </h4>

##### Slicing

In [28]:
slice_array = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18]])

In [29]:
# From the first element, get all elements starting from the third position.

print(slice_array[0,3:])

[4 5 6]


In [30]:
# Get the third position in each element.

print(slice_array[0:,3])

[ 4 10 16]


In [31]:
# Get the three first elements from the first two elements.

print(slice_array[0:2,0:3])

[[1 2 3]
 [7 8 9]]


In [32]:
# Replace the first three elements in the third element with 100, 200 and 300
replace = np.array([100, 200, 300])

slice_array[2,:3] = replace
print(slice_array)

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [100 200 300  16  17  18]]


In [33]:
# Replace the two middle elements in the second and third element with zeros.

replace = np.zeros(4).reshape(2, 2)

slice_array[1:3,2:4] = replace
print(slice_array)

[[  1   2   3   4   5   6]
 [  7   8   0   0  11  12]
 [100 200   0   0  17  18]]


##### Stacking

Stacking allows you to stack arrays into one array. Vertical stacking stacks the arrays without changing the number of columns. Horizontal stacking stacks the arrays without changing the number of rows. 

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [6, 7]])

print("vertical stacking : \n", np.vstack((a, b))) # Use .vstack for vertical stacking
print("\nhorizontal stacking : \n", np.hstack((a, b))) # Use .hstack for horizontal stacking

vertical stacking : 
 [[1 2]
 [3 4]
 [5 6]
 [6 7]]

horizontal stacking : 
 [[1 2 5 6]
 [3 4 6 7]]


##### Insert

In [35]:
# Use insert if you want to insert a element into a specific place.

insert_array = np.array([[1, 2], [3, 4], [7, 8]])
missing_element = np.array([5, 6])

print(np.insert(insert_array, 2, missing_element, axis = 0)) #insert missing_element into insert_array at index 2 and axis = 0.

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
# Inserting horizontally.

insert_array = np.array([[1, 2, 4], [5, 6, 8], [9, 10, 12]])
missing_element = np.array([3, 7, 11])

print(np.insert(insert_array, 2, missing_element, axis = 1)) #insert missing_element into insert_array at index 2 and axis = 1.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h4>2.6 Question Time! </h4>

In [37]:
#Q1 Print the middle three values of the following array
arr = [1, 2, 3, 4, 5 ,6, 7 ,8, 9]

In [42]:
#Q1 Your answer here:
print(arr[3:6])


[4, 5, 6]


<p>Q1 Expected output: </p>

<pre>[4, 5, 6]
</pre>

In [39]:
#Q2 What is the sum of the third row in the following array?
sum_array = np.array([[10, 15, 20, 25, 30], [40, 45, 50, 55, 60], [70, 75, 80, 85, 90], [100, 105, 110, 115, 120]])

In [43]:
#Q2 Your answer here:
print(np.sum(sum_array[2,:]))



400


<p>Q2 Expected output: </p>

<pre>400
</pre>

Q3 Recreate this array (without just manually declaring this exact array): 

<pre>[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]</pre>

In [46]:
#Q3 Your answer here: 
array = np.ones((5,5))
zeros = np.zeros((3, 3))

array[1:4,1:4] = zeros
array[2,2] = 9
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


<p>Q3 Expected output: </p>

<pre>[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]</pre>

In [49]:
#Q4 Insert the missing row in this sudoku. Bonus points if you insert it in the correct place but not required. 

unfinished_sudoku = np.array([[3, 1, 6, 5, 7, 8, 4, 9, 2], 
[5, 2, 9, 1, 3, 4, 7, 6, 8], 
[4, 8, 7, 6, 2, 9, 5, 3, 1], 
[2, 6, 3, 4, 1, 5, 9, 8, 7], 
[8, 5, 1, 7, 9, 2, 6, 4, 3], 
[1, 3, 8, 9, 4, 7, 2, 5, 6], 
[6, 9, 2, 3, 5, 1, 8, 7, 4],
[7, 4, 5, 2, 8, 6, 3, 1, 9]])

missing_row = [9, 7, 4, 8, 6, 3, 1, 2, 5]

In [52]:
#Q4 Your answer here: 
print(np.insert(unfinished_sudoku, 2, missing_row, axis = 0))


[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [9 7 4 8 6 3 1 2 5]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]


<p>Q4 Expected output: </p>

<pre>[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
</pre>

In [53]:
#Q5 Sort this array by ascending
sort_arr = np.array([1, 6, 34, 7, 2, 99, 46, 84, 23])

In [54]:
#Q5 Your answer here:
print(np.sort(sort_arr))


[ 1  2  6  7 23 34 46 84 99]


<p>Q5 Expected output: </p>

<pre>[ 1  2  6  7 23 34 46 84 99]
</pre>

In [55]:
#Q6 How many rows and how many columns does this array have?

array = np.array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [56]:
#Q6 Your answer here:
print(np.shape(array))


(4, 50)


<p>Q6 Expected output: </p>

<pre>(4, 50)
</pre>

In [64]:
#Q7 Change this array so that each number is increased by one from the previous (1, 2, 3, 4 .... 21, 22, 23, 24)

increase_array = np.array([[1, 1, 1, 1], [5, 5, 5, 5], [9, 9, 9, 9], [13, 13, 13, 13], [17, 17, 17, 17], [21, 21, 21, 21]])

In [65]:
#Q7 Your answer here:
a = np.array([0,1,2,3])
increase_array += a
print(increase_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


<p>Q7 Expected output: </p>

<pre>[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
</pre>

In [66]:
#Q8 Create an array with integers 1-20 and reshape it so it has 4 rows and 5 columns.

In [75]:
#Q8 Your answer here:
a = np.arange(1,21)
print(np.reshape(a,[4,5]))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


<p>Q8 Expected output: </p>

<pre>[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
</pre>

In [76]:
#Q9 Create the expected output using the arrays in this cell and by using stacking. 

a = [[1, 2]]
b = [[3, 4]]
c = [[5, 6]]
d = [[7, 8]]


In [101]:
#Q9 You answer here:
print(a[0])
print(np.hstack(((a[0],c[0]),(b[0],d[0]))))


[1, 2]
[[1 2 3 4]
 [5 6 7 8]]


<p>Q9 Expected output: </p>

<pre>[[1 2 3 4]
 [5 6 7 8]]
</pre>

In [87]:
#Q10 How many dimensions has the following array? 

dimension_array = np.arange(6400).reshape(4, 4, 5, 8, 1, 10)

In [89]:
#Q10 Your answer here: 
print(len(np.shape(dimension_array)))

6


<p>Q10 Expected output: </p>

<pre>6
</pre>