## Solution Proposal

In [8]:
import numpy as np

In [9]:
#Q1 Answer:
arr = [1, 2, 3, 4, 5 ,6, 7 ,8, 9]

arr[3:6]

[4, 5, 6]

In [10]:
#Q2 Answer:
sum_array = np.array([[10, 15, 20, 25, 30], [40, 45, 50, 55, 60], [70, 75, 80, 85, 90], [100, 105, 110, 115, 120]])

sum_array.sum(axis=1)[2]

400

In [29]:
#Q3 Answer: 
a = np.ones((5, 5), dtype=np.int16)

b = np.zeros((3, 3), dtype=np.int16)
b[1, 1] = 9

a[1:4, 1:4] = b
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [27]:
#Q4 Answer 
unfinished_sudoku = np.array([[3, 1, 6, 5, 7, 8, 4, 9, 2], 
[5, 2, 9, 1, 3, 4, 7, 6, 8], 
[4, 8, 7, 6, 2, 9, 5, 3, 1], 
[2, 6, 3, 4, 1, 5, 9, 8, 7], 
[8, 5, 1, 7, 9, 2, 6, 4, 3], 
[1, 3, 8, 9, 4, 7, 2, 5, 6], 
[6, 9, 2, 3, 5, 1, 8, 7, 4],
[7, 4, 5, 2, 8, 6, 3, 1, 9]])

missing_row = [9, 7, 4, 8, 6, 3, 1, 2, 5]

row = 4
print(np.insert(unfinished_sudoku, row, missing_row, axis=0))

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]


In [31]:
#Q5 Answer
sort_arr = np.array([1, 6, 34, 7, 2, 99, 46, 84, 23])

print(np.sort(sort_arr))

[ 1  2  6  7 23 34 46 84 99]


In [14]:
#Q6 Answer
array = np.array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

array.shape

(4, 50)

In [17]:
#Q7 Answer
increase_array = np.array([[1, 1, 1, 1], [5, 5, 5, 5], [9, 9, 9, 9], [13, 13, 13, 13], [17, 17, 17, 17], [21, 21, 21, 21]])

increase = [0,1,2,3]
increase_array += increase
print(increase_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [30]:
#Q8 Answer

a = np.arange(20)
a+=1
a = a.reshape(4, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
# Q9 Answer

a = [[1, 2]]
b = [[3, 4]]
c = [[5, 6]]
d = [[7, 8]]

i = np.hstack((a, b))
j = np.hstack((c, d))
print(np.vstack((i, j)))

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
# Q10 Answer

dimension_array = np.arange(6400).reshape(4, 4, 5, 8, 1, 10)
dimension_array.ndim

6